In [270]:


temps = np.array([
    -4, -3, 2, 9, 15, 19,
    21, 20, 14, 8, 2, -2
])

print(temps)

[-4 -3  2  9 15 19 21 20 14  8  2 -2]


In [271]:
days_in_month = np.array([
    31, 28, 31, 30, 31, 30,
    31, 31, 30, 31, 30, 31
])

print(days_in_month)
warm_days = days_in_month[temps > 15]

print("Кількість днів у теплих місяцях:")
print(warm_days)

print("Всього днів:", warm_days.sum())

[31 28 31 30 31 30 31 31 30 31 30 31]
Кількість днів у теплих місяцях:
[30 31 31]
Всього днів: 92


In [272]:
month_numbers = np.arange(1, 13)

print(month_numbers)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [273]:
print("temps:")
print("shape:", temps.shape)
print("dtype:", temps.dtype)

print("\ndays_in_month:")
print("shape:", days_in_month.shape)
print("dtype:", days_in_month.dtype)

print("\nmonth_numbers:")
print("shape:", month_numbers.shape)
print("dtype:", month_numbers.dtype)

temps:
shape: (12,)
dtype: int64

days_in_month:
shape: (12,)
dtype: int64

month_numbers:
shape: (12,)
dtype: int64


In [274]:
temps_f = temps * 9 / 5 + 32

print("Температура у °F:")
print(temps_f)
print(temps > 15)

Температура у °F:
[24.8 26.6 35.6 48.2 59.  66.2 69.8 68.  57.2 46.4 35.6 28.4]
[False False False False False  True  True  True False False False False]


In [275]:
total_days = days_in_month.sum()

print("Всього днів:", total_days)
print("Чи дорівнює 365:", total_days == 365)

Всього днів: 365
Чи дорівнює 365: True


In [276]:
max_temp = temps.max()
max_index = temps.argmax()

print("Найвища температура:", max_temp, "°C")
print("Індекс:", max_index)
print("Номер місяця:", month_numbers[max_index])

Найвища температура: 21 °C
Індекс: 6
Номер місяця: 7


In [277]:
min_temp = temps.min()
min_index = temps.argmin()

print("Найнижча температура:", min_temp, "°C")
print("Індекс:", min_index)
print("Номер місяця:", month_numbers[min_index])

Найнижча температура: -4 °C
Індекс: 0
Номер місяця: 1


In [278]:
negative_months = month_numbers[temps < 0]

print("Місяці з температурою нижче 0°C:")
print(negative_months)

Місяці з температурою нижче 0°C:
[ 1  2 12]


In [279]:
sorted_temps = np.sort(temps)

print("Відсортовані температури:")
print(sorted_temps)

print("\nОригінальний масив:")
print(temps)

Відсортовані температури:
[-4 -3 -2  2  2  8  9 14 15 19 20 21]

Оригінальний масив:
[-4 -3  2  9 15 19 21 20 14  8  2 -2]


In [280]:
sun_hours = np.array([
    55, 70, 110, 150, 210, 230,
    250, 240, 170, 120, 70, 50
])

print(sun_hours)

[ 55  70 110 150 210 230 250 240 170 120  70  50]


In [281]:
data = np.array([
    temps,
    days_in_month,
    sun_hours
])

print(data)
print("shape:", data.shape)

[[ -4  -3   2   9  15  19  21  20  14   8   2  -2]
 [ 31  28  31  30  31  30  31  31  30  31  30  31]
 [ 55  70 110 150 210 230 250 240 170 120  70  50]]
shape: (3, 12)


In [282]:
row_sums = data.sum(axis=1)

print("Сума кожного рядка:")
print(row_sums)

Сума кожного рядка:
[ 101  365 1725]


In [283]:
row_means = data.mean(axis=1)

print("Середнє кожного рядка:")
print(row_means)

Середнє кожного рядка:
[  8.41666667  30.41666667 143.75      ]


In [284]:
column_sums = data.sum(axis=0)

print("Сума кожного стовпця:")
print(column_sums)

Сума кожного стовпця:
[ 82  95 143 189 256 279 302 291 214 159 102  79]


In [285]:
print("Сума за січень:", column_sums[0])

Сума за січень: 82


In [286]:
rows = np.array([
    temps,
    days_in_month
])

print(rows)
print("shape:", rows.shape)

[[-4 -3  2  9 15 19 21 20 14  8  2 -2]
 [31 28 31 30 31 30 31 31 30 31 30 31]]
shape: (2, 12)


In [287]:
correction = np.array([1, 0])

print(correction)
print("shape:", correction.shape)

[1 0]
shape: (2,)


In [288]:
rows + correction

ValueError: operands could not be broadcast together with shapes (2,12) (2,) 

In [268]:
correction_reshaped = correction.reshape(2, 1)

print(correction_reshaped)
print("shape:", correction_reshaped.shape)

[[1]
 [0]]
shape: (2, 1)


In [269]:
result = rows + correction_reshaped

print("Результат:")
print(result)

Результат:
[[-3 -2  3 10 16 20 22 21 15  9  3 -1]
 [31 28 31 30 31 30 31 31 30 31 30 31]]


1. Різниця між shape == (12,) і shape == (1, 12)

(12,) — це одновимірний масив із 12 елементів. (1, 12) — це двовимірний масив, який має 1 рядок і 12 стовпців. Вони мають однакову кількість елементів, але різну кількість вимірів.

2. Чому temps[temps > 15] повертає масив іншої довжини?

temps > 15 створює булеву маску. При булевій індексації залишаються тільки ті елементи, для яких умова має значення True. Тому результат містить тільки температури вище 15°C і може бути коротшим за початковий масив із 12 елементів.

3. Що станеться при додаванні (3,) до (3, 12)?

Виникне помилка broadcasting, тому що NumPy порівнює розміри справа наліво. Розміри 12 і 3 несумісні. Щоб виконати додавання одного значення до кожного рядка, масив (3,) потрібно перетворити на (3, 1).

4. Чому rows + correction дає помилку, а rows + correction.reshape(2, 1) працює?

rows має форму (2, 12), а correction має форму (2,). Розміри 12 і 2 несумісні, тому виникає помилка. Після reshape(2, 1) форми стають (2, 12) і (2, 1). Розмір 1 може бути розширений до 12, тому broadcasting дозволяє виконати операцію.