Практика 1. Робоче середовище і NumPy

Варіант 4 — Харків

Практична робота з масивами NumPy та векторизованими обчисленнями.

In [44]:
a = np.array([1, 2, 3, 4, 5])

print(a)
print("shape:", a.shape)
print("dtype:", a.dtype)


[1 2 3 4 5]
shape: (5,)
dtype: int64


In [38]:
# Завдання 1. Створення масивів

# Температури Харкова за місяцями
temps = np.array([-6, -5, 1, 10, 17, 20, 22, 21, 15, 8, 1, -4])

# Кількість днів у кожному місяці невисокосного року
days_in_month = np.array([31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31])

# Номери місяців від 1 до 12
month_numbers = np.arange(1, 13)

print("temps:")
print(temps)
print("shape:", temps.shape)
print("dtype:", temps.dtype)

print("\ndays_in_month:")
print(days_in_month)
print("shape:", days_in_month.shape)
print("dtype:", days_in_month.dtype)

print("\nmonth_numbers:")
print(month_numbers)
print("shape:", month_numbers.shape)
print("dtype:", month_numbers.dtype)


temps:
[-6 -5  1 10 17 20 22 21 15  8  1 -4]
shape: (12,)
dtype: int64

days_in_month:
[31 28 31 30 31 30 31 31 30 31 30 31]
shape: (12,)
dtype: int64

month_numbers:
[ 1  2  3  4  5  6  7  8  9 10 11 12]
shape: (12,)
dtype: int64


In [39]:
# Завдання 2. Векторизовані обчислення

# Переведення температури з °C у °F
temps_f = temps * 9 / 5 + 32

print("Температура у °F:")
print(temps_f)

# Місяці, де температура вище 15°C
warm_months = temps > 15

print("\nБулева маска для температур > 15°C:")
print(warm_months)

# Кількість днів у таких місяцях
warm_days = days_in_month[warm_months]

print("\nКількість днів у теплих місяцях:")
print(warm_days)

print("Всього днів із температурою вище 15°C:", warm_days.sum())

# Перевірка кількості днів у році
print("\nСума днів у році:", days_in_month.sum())
print("Чи дорівнює 365:", days_in_month.sum() == 365)


Температура у °F:
[21.2 23.  33.8 50.  62.6 68.  71.6 69.8 59.  46.4 33.8 24.8]

Булева маска для температур > 15°C:
[False False False False  True  True  True  True False False False False]

Кількість днів у теплих місяцях:
[31 30 31 31]
Всього днів із температурою вище 15°C: 123

Сума днів у році: 365
Чи дорівнює 365: True


In [40]:
# Завдання 3. Індексація і фільтрація

# Найвища температура
max_temp = temps.max()
max_index = temps.argmax()

print("Найтепліший місяць:")
print("Температура:", max_temp, "°C")
print("Індекс:", max_index)
print("Номер місяця:", month_numbers[max_index])

# Найнижча температура
min_temp = temps.min()
min_index = temps.argmin()

print("\nНайхолодніший місяць:")
print("Температура:", min_temp, "°C")
print("Індекс:", min_index)
print("Номер місяця:", month_numbers[min_index])

# Місяці з температурою нижче 0°C
below_zero_months = month_numbers[temps < 0]

print("\nНомери місяців з температурою нижче 0°C:")
print(below_zero_months)

# Сортування температур
sorted_temps = np.sort(temps)

print("\nТемператури за зростанням:")
print(sorted_temps)

print("\nОригінальний масив temps:")
print(temps)


Найтепліший місяць:
Температура: 22 °C
Індекс: 6
Номер місяця: 7

Найхолодніший місяць:
Температура: -6 °C
Індекс: 0
Номер місяця: 1

Номери місяців з температурою нижче 0°C:
[ 1  2 12]

Температури за зростанням:
[-6 -5 -4  1  1  8 10 15 17 20 21 22]

Оригінальний масив temps:
[-6 -5  1 10 17 20 22 21 15  8  1 -4]


In [41]:
# Завдання 4. Двовимірний масив і axis

# Умовна кількість сонячних годин за місяць
sun_hours = np.array([45, 65, 110, 160, 220, 240, 250, 230, 170, 120, 60, 40])

# Об'єднуємо три рядки в один двовимірний масив
data = np.array([temps, days_in_month, sun_hours])

print("Двовимірний масив:")
print(data)

print("\nФорма data:")
print(data.shape)

# Сума по кожному рядку
print("\nСума по кожному рядку (axis=1):")
print(data.sum(axis=1))

# Середнє по кожному рядку
print("\nСереднє по кожному рядку (axis=1):")
print(data.mean(axis=1))

# Сума по кожному стовпцю
print("\nСума по кожному стовпцю (axis=0):")
print(data.sum(axis=0))


Двовимірний масив:
[[ -6  -5   1  10  17  20  22  21  15   8   1  -4]
 [ 31  28  31  30  31  30  31  31  30  31  30  31]
 [ 45  65 110 160 220 240 250 230 170 120  60  40]]

Форма data:
(3, 12)

Сума по кожному рядку (axis=1):
[ 100  365 1710]

Середнє по кожному рядку (axis=1):
[  8.33333333  30.41666667 142.5       ]

Сума по кожному стовпцю (axis=0):
[ 70  88 142 200 268 290 303 282 215 159  91  67]


In [42]:
# Завдання 5. reshape і broadcasting

# Масив із двох рядків
rows = np.array([temps, days_in_month])

print("rows:")
print(rows)

print("\nФорма rows:")
print(rows.shape)

# Масив поправок
correction = np.array([1, 0])

print("\ncorrection:")
print(correction)

print("Форма correction:")
print(correction.shape)

# Спроба додавання
try:
    result = rows + correction
    print(result)
except ValueError as e:
    print("\nВиникла помилка:")
    print(e)


rows:
[[-6 -5  1 10 17 20 22 21 15  8  1 -4]
 [31 28 31 30 31 30 31 31 30 31 30 31]]

Форма rows:
(2, 12)

correction:
[1 0]
Форма correction:
(2,)

Виникла помилка:
operands could not be broadcast together with shapes (2,12) (2,) 


In [45]:
# Змінюємо форму correction
correction_2d = correction.reshape(2, 1)

print("Нова форма correction:")
print(correction_2d.shape)

# Додаємо поправки
result = rows + correction_2d

print("\nРезультат:")
print(result)

print("\nФорма результату:")
print(result.shape)


Нова форма correction:
(2, 1)

Результат:
[[-5 -4  2 11 18 21 23 22 16  9  2 -3]
 [31 28 31 30 31 30 31 31 30 31 30 31]]

Форма результату:
(2, 12)


Відповіді на контрольні питання
1. Різниця між shape == (12,) і shape == (1, 12)

shape == (12,) означає одновимірний масив із 12 елементів. Він має одну вісь.

shape == (1, 12) означає двовимірний масив із 1 рядком і 12 стовпцями. Кількість елементів однакова, але структура масиву різна.

2. Чому temps[temps > 15] має іншу довжину?

Вираз temps > 15 створює булеву маску. Для кожної температури отримуємо True або False.

Під час булевої індексації NumPy залишає тільки елементи, для яких отримано True. Тому результат містить лише температури, що перевищують 15°C, і має меншу довжину, ніж початковий масив temps.

3. Що станеться при додаванні масиву (3,) до (3, 12)?

При broadcasting NumPy порівнює форми справа наліво. Форми (3, 12) та (3,) можна розглядати як (3, 12) та (1, 3).

Числа 12 і 3 несумісні, тому виникне помилка broadcasting.

Щоб додати по одному значенню до кожного з трьох рядків, потрібно використати масив форми (3, 1).

4. Чому rows + correction дає помилку, а rows + correction.reshape(2, 1) працює?

rows має форму (2, 12), а correction — (2,). При порівнянні останніх вимірів отримуємо 12 і 2, які несумісні.

Після correction.reshape(2, 1) форма стає (2, 1). Тепер NumPy може розширити вимір 1 до 12, тому форми (2, 12) та (2, 1) стають сумісними.

Отже, кожна поправка застосовується до всіх 12 елементів відповідного рядка.